// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadUpdate(arg1) {
  return window['go']['state']['State']['DownloadUpdate'](arg1);
}

export function GetAppVersion() {
  return window['go']['state']['State']['GetAppVersion']();
}

export function HandleUSBConnectionEvent(arg1, arg2) {
  return window['go']['state']['State']['HandleUSBConnectionEvent'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['state']['State']['InstallUpdate']();
}

export function Log(arg1, arg2) {
  return window['go']['state']['State']['Log'](arg1, arg2);
}

export function Open(arg1) {
  return window['go']['state']['State']['Open'](arg1);
}

export function Quit() {
  return window['go']['state']['State']['Quit']();
}

export function Reset() {
  return window['go']['state']['State']['Reset']();
}

export function SelectDevice(arg1) {
  return window['go']['state']['State']['SelectDevice'](arg1);
}

export function SelectFirmware() {
  return window['go']['state']['State']['SelectFirmware']();
}

export function SetStep(arg1) {
  return window['go']['state']['State']['SetStep'](arg1);
}

export function StartFlashing() {
  return window['go']['state']['State']['StartFlashing']();
}

export function StateStart() {
  return window['go']['state']['State']['StateStart']();
}

export function Teardown() {
  return window['go']['state']['State']['Teardown']();
}
